django/0327/crud/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:pk>/comments/<int:comment_pk>/delete', views.comments_delete, name='comments_delete')
]

django/0327/crud/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

django/0327/crud/articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'
        exclude = ('user',)

class CommnetForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ('user', 'article',)

django/0327/crud/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommnetForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST, require_safe


# Create your views here.

@require_safe
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)


@require_safe
def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comment_form = CommnetForm()
    comments = article.comment_set.all()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)


@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article.pk)

    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form,
    }
    return render(request, 'articles/update.html', context)


@require_POST
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return redirect('articles:index')


@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        comment_form = CommnetForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
            return redirect('articles:detail', article.pk)
        context = {
            'article': article,
            'comment_form': comment_form,
        }
        return render(request, 'articles/detail.html', context)
    return redirect('accounts:login')


@require_POST
def comments_delete(request, pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        comment.delete()
    return redirect('articles:detail', pk)

django/0327/crud/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block content %}
  <h2>CREATE PAGE</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>create</button>
  </form>
{% endblock content %}

django/0327/crud/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block content %}
  <h2>DETAIL PAGE</h2>
  <p>user : {{ article.user.username }}</p>
  <p>title : {{ article.title }}</p>
  <p>content : {{ article.content }}</p>
  <p>created_at : {{ article.created_at }}</p>
  <p>updated_at : {{ article.updated_at }}</p>
  <a href="{% url 'articles:update' article.pk %}">UPDATE</a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <button>DELETE</button>
  </form>
  <hr>
  <p>{{ comments|length }}개의 댓글이 있습니다.</p>
  {% for comment in comments %}
    <p>{{ comment.user }}</p>
    <p>{{ comment.content }}</p>
    <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
      {% csrf_token %}
      <button>COMMENT DELETE</button>
    </form>
  {% endfor %}
  <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
    {% csrf_token %}
    {{ comment_form }}
    <button>COMMENT CREATE</button>
  </form>
  <a href="{% url 'articles:index' %}">BACK</a>
{% endblock content %}

django/0327/crud/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block content %}
  <h2>INDEX PAGE</h2>
  <a href="{% url 'articles:create' %}">create</a>
  {% for article in articles %}
    <p>{{ article.title }}</p>
    <p>{{ article.content }}</p>
    <a href="{% url 'articles:detail' article.pk %}">DETAIL</a>
  {% endfor %}
{% endblock content %}

django/0327/crud/articles/templates/articles/update.html
{% extends 'base.html' %}
{% block content %}
  <h2>UPDATE PAGE</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>update</button>
  </form>
{% endblock content %}