django/0319/pinterest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # static('media/', document_root=settings.MEDIA_ROOT)

django/0319/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
]

django/0319/posts/models.py
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(blank=True)
    # image_thumbnail = ImageSpecField(
    #     source='image',
    #     processors=[ResizeToFill(200, 200)],
    #     format='JPEG',
    #     options={
    #         'quality': 60
    #     },
    # )
    image = ProcessedImageField(
        upload_to='images/%Y/%m/%d/',
        processors=[ResizeToFill(500, 500)],
        format='JPEG',
        options={
            'quality': 60
        }
    )
    created_at = models.DateTimeField(auto_now_add=True)

django/0319/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = '__all__'

django/0319/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from .forms import PostForm
from .models import Post

# Create your views here.
def index(request):
    posts = Post.objects.all()

    context = {
        'posts': posts,
    }

    return render(request, 'posts/index.html', context)


@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'posts/form.html', context)


def detail(request, pk):
    # post = Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    context = {
        'post': post,
    }

    return render(request, 'posts/detail.html', context)


def update(request, pk):
    # post = Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm(instance=post)
    context = {
        'form': form,
    }
    return render(request, 'posts/form.html', context)

django/0319/posts/templates/posts/_card.html
<div class="card">
  
  {% if post.image %}
    <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.image }}">
  {% else %}
    <img src="/media/lion.jpg" class="card-img-top" alt="">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title text-center">
      <a href="{% url 'posts:detail' post.pk %}" class="btn">{{ post.title }}</a> 
    </h5>  
  </div>
</div>

django/0319/posts/templates/posts/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <div class="fs-3 text-center bg-info p-3">create</div>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-primary" type="submit">
  </form>
{% endblock content %}

django/0319/posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block content %}
  {% if post.image %}
    <img src="{{ post.image.url }}" alt="{{ post.image }}" width="100%">
  {% else %}
    <h1>이미지가 없습니다.</h1>
  {% endif %}
  <div class="bg-light fs-4 w-100 text-center my-2 p-5">{{ post.content }}</div>
  <div class="d-flex justify-content-center my-3">
    <a class="btn btn-warning" href="{% url 'posts:update' post.pk %}">수정</a>
    <a class="btn btn-danger" href="{% url 'posts:update' post.pk %}">삭제</a>
  </div>

{% endblock content %}

django/0319/posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  {% if request.resolver_match.url_name == 'create' %}
    <div class="fs-3 text-center bg-info p-3">create</div>
  {% else %}
    <div class="fs-3 text-center bg-warning p-3">update</div>
  {% endif %}
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-primary" type="submit">
  </form>
{% endblock content %}

django/0319/posts/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for post in posts %}
      <div class="col">
        {% include 'posts/_card.html' %}
      </div>
    {% empty %}
      <div class="bg-light fs-1 w-100 text-center my-5 p-5">empty</div>
    {% endfor %}
  </div>
{% endblock content %}

django/0319/posts/templates/posts/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <div class="fs-3 text-center bg-warning p-3">update</div>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-primary" type="submit">
  </form>
{% endblock content %}