django/0318/django_static/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete')
]

django/0318/django_static/articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    # image = models.ImageField(upload_to='images/%Y/%m/%d/', blank=True)
    image = ProcessedImageField( # 원본을 사용하지 않을 때 사용
        blank=True,
        processors=[Thumbnail(100, 100)], # 썸네일 크기
        format='JPEG', # jpeg 로 처리
        options={
            'quality': 80, # 기존 이미지를 80% 압축
        }
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

django/0318/django_static/articles/forms.py
from django import forms
from .models import Article
# class ArticleForm(forms.Form):
#     title = forms.CharField(max_length=10)
#     content = forms.CharField(widget=forms.Textarea)

class ArticleForm(forms.ModelForm):
    # form 꾸미기
    title = forms.CharField(
        label="제목",
        widget=forms.TextInput(
            attrs={
                'class': 'my-title abc',
                'placeholder': "제목을 10자로 적어주세요.",
            }
        )
    )

    content = forms.CharField(
        label="내용",
        widget=forms.Textarea(
            attrs={
                'class': 'my-content',
                'placeholder': '내용을 적어주세요.',
            }
        )
    )
    # 메타 데이터를 저장하는 class
    class Meta:
        model = Article
        # 원하는 필드만 입력받을 경우
        # field = ('title', 'content')
        # 모든 필드를 입력받고 싶은 경우
        fields = '__all__'

django/0318/django_static/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm

# Create your views here.

def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


# def new(request):
#     form = ArticleForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'articles/new.html', context)


# def create(request):
#     # 값을 받아서 폼 인스턴스 생성
#     form = ArticleForm(request.POST)

#     # 유효성 검사
#     if form.is_valid():
#         # DB에 저장 (Form 으로 작성했을 때)
#         # title = form.cleaned_data.get('title')
#         # content =form.cleaned_data.get('content')
#         # article = Article(title=title, content=content)
#         # article.save()

#         # DB에 저장 (Model Form 으로 작성했을 때)
#         article = form.save() # 저장된 데이터의 인스턴스를 return 한다

#         return redirect('articles:index')
    
#     context = {
#         'form': form,
#     }
#     return render(request, 'articles/new.html', context)


def create(request):
    if request.method == "POST":
        # def create : DB 에 저장하는 동작
        form = ArticleForm(request.POST, request.FILES)

        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)

    else:
        # def new : page 를 보여주는 동작 (new 는 GET 으로 요청하기 때문에)
        form = ArticleForm()

    context = {
        'form': form,
    }
    return render(request, 'articles/new.html', context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)


def edit(request, pk):
    article = Article.objects.get(pk=pk)

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article) # instance 로 article 을 받아와야 기존의 값을 수정할 수 있다.
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)

    else:
        form = ArticleForm(instance=article) # article 정보로 form을 생성해 준다.

    context = {
        'form': form,
        'article':article,
    }
    return render(request, 'articles/edit.html', context)


def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')

    return redirect('articles:detail', article.pk)

django/0318/django_static/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block content %}
  <p>TITLE : {{ article.title }}</p>
  <p>CONTENT : {{ article.content }}</p>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="{{ article.image }}">
  {% endif %}
  <hr>
  <a href="{% url 'articles:index' %}">BACK</a>
  <a href="{% url 'articles:edit' article.pk %}">EDIT</a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <button>DELETE</button>
  </form>
{% endblock content %}

django/0318/django_static/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% block content %}
<h2>EDIT</h2>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button>수정</button>
  <br>
  <a href="{% url 'articles:detail' article.pk %}">BACK</a>
</form>
{% endblock content %}

django/0318/django_static/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'articles/css/index.css' %}">
{% endblock css %}

{% block content %}
<h2 class="blue">INDEX</h2>
<img src="{% static 'articles/img/sample.jpg' %}" alt="sample">
<a href="{% url 'articles:create' %}">NEW</a>
<hr>
<ol>
  {% for article in articles %}
    <li>{{ article.title }}</li>
    <a href="{% url 'articles:detail' article.pk %}">DETAIL</a>
  {% endfor %}
</ol>
{% endblock content %}

django/0318/django_static/articles/templates/articles/new.html
{% extends 'base.html' %}
{% block content %}
<h2>NEW</h2>
<hr>
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button>글작성</button>
</form>
  <br>
  <a href="{% url 'articles:index' %}">BACK</a>
</form>
{% endblock content %}